### ISSUE TITLE
Bad Gateway few minutes after start

### ISSUE THREAD

**Issue by sadmin91** [chrootlogin/docker-nextcloud#55]
Hello,

I have installed last version (Nextcloud 20.0.4) on my Raspberry Pi 4 (ubuntu); and few minutes after start (where all works fine), I was block with and HTTP 502 "Bad Gateway" error.

To analyze this problem, I have attached: 

- a log file (https://github.com/chrootlogin/docker-nextcloud/files/5795306/Nextcloud_20.0.4_HTTP502_BadGateway_20210111.log)
- a screenshot (https://user-images.githubusercontent.com/6031110/104172256-46d68b80-5404-11eb-8431-8cc2eb2b5b95.png)

**Comment by sadmin91** [comment]
I have found a solution for this problem:
> On nginx.conf, I have added theses instructions after fastcgi_pass instruction:
> fastcgi_buffer_size 128k;
> fastcgi_buffers 4 256k; 

Do you think that this modification could be added to this repo?

**Comment by chrootlogin** [comment]
Hi @sadmin91 

Thanks for reaching me out. Can you please give me more details about your clients? What client or clients are you using?

```
2021/01/11 10:38:52 [error] 18#18: *1954 upstream sent too big header while reading response header from upstream, client: 10.0.1.55, server: , request: "GET /apps/files/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "nextcloud.mydomain.fr"
```

"upstream sent too big header" suggest a wrong behaving client to me. Can you give me more insight?

Apart from that: Yes we could increase the buffer sizes as recommended by you. In the moment it's configured with the values recommended by the nextcloud admin manual. But first let us check if it's a client problem.

Best regards
Simon

**Comment by sadmin91** [comment]
Hello,
When the problem occurs, I have only one client: I was been connected to Nextcloud UI on my Web Browser (Firefox).
Regards

**Comment by chrootlogin** [comment]
Okay.

After searching a bit and checking out https://gist.github.com/magnetikonline/11312172 it turns out that changing fastcgi_buffers can have some unattended side-effects and needs to be done carefully.

So I analyzed a bit my traffic patterns and found out that we have an average response size on logins requests of about 4558 byte which exceeds the buffer size of 4096 byte. Because of this I changed the buffer to be 8k but leaving the rest as is.

Can you check the development build (`docker run rootlogin/nextcloud:develop`) and give me feedback if it solves your problem? (Please do a login-logout cycle because this seems to create big responses.)

Best regards

**Comment by sadmin91** [comment]
Hello,
I have installed the development build and I don't reproduce this behaviour.
This is fine!

Thank you for your correction.

**Comment by chrootlogin** [comment]
Hello

Thank you very much for your feedback! That sounds perfect! So I will merge it to master.

Best regards.
