### ISSUE TITLE
update to nextcloud 22

### ISSUE THREAD

**Issue by onny** [chrootlogin/docker-nextcloud#59]

**Comment by ccellist** [comment]
You can actually build this image based on any version of nextcloud as long as you add `--build-arg NEXTCLOUD_VERSION=<desired version>` to your build command. Personally I added a build stanza to my docker-compose file so I don't have to think about it. I just update the version and `docker-compose build`. I can't guarantee results since I am not a maintainer, but it's worked for me so far.

**Comment by chrootlogin** [comment]
This image has been moved to [erhardtconsulting/nextcloud](https://github.com/erhardtconsulting/images/tree/main/nextcloud) and is now rootless and compatible with Kubernetes.
